Content Negotiation for Express.js HTTP Thing
eclipse-thingweb/test-things pull request #16
Opened 2023-11-14 14:24 UTC by SergioCasCeb

- Modified the HTTP Thing to include headers for content negotiation (Text, JSON, and CBOR)
- Reflected such information on the generated TD
- Created a simple client to test the functionality of the Thing

2023-11-17 13:26 UTC, egekorkan requested changes
1. We should reduce content types to cbor and json since more means more forms in each affordance.
2. We should have another Thing code for content negotiation since we are complicating the simple protocol Thing. We should probably do this for all Things we have. Each protocol has more complex/edge cases in addition to simple ones. Trying to put all mechanisms into one Thing worsens the experience for users who want to test simple mechnanisms.

2023-11-17 13:26 UTC, egekorkan commented
The comment and changes above will apply to CoAP as well.

2023-11-22 13:54 UTC, danielpeintner commented on things/calculator/http/client/README.md
> +## Enpoints Simple Calculator Thing
```suggestion
## Endpoints Simple Calculator Thing
```

I think I noted that somewhere else already..

2023-11-22 13:54 UTC, danielpeintner commented on things/calculator/http/client/README.md
> +## Enpoints Content Negotiation Calculator Thing
```suggestion
## Endpoints Content Negotiation Calculator Thing
```

2023-11-27 13:58 UTC, egekorkan requested changes
An initial review. I will test locally later as well.

2023-12-04 08:47 UTC, danielpeintner commented on things/calculator/http/client-tests/content-negotiation-http-client.js
> + * @file The `content-negotiation-http-client.js` file acts a client for the content-negotiation-calculator.js.
```suggestion
 * @file The `content-negotiation-http-client.js` file acts as a client for the content-negotiation-calculator.js.
```

2023-12-11 16:49 UTC, egekorkan commented
Last fixes:
- Method not allowed should be added
- JSON Schema based validation should be used instead of type casting. Currently, sending `"1"` is the same as sending `1`.
- date-time should be used for last change and it should be formatted to match one of the version noted at https://json-schema.org/understanding-json-schema/reference/string#dates-and-times
- SSE endpoints for property observation does not work. For now, let's do observation with another endpoint (/result/observe). We will come to this when it is clarified within the spec

2024-03-08 17:21 UTC, egekorkan commented
Merging. All tests pass now :)

2024-03-08 17:21 UTC, merged